{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "health-master.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "health-master.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "health-master.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
