Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60s
  WriteTimeout: 60s
Database:
  URL: postgres://postgres:123456@127.0.0.1:5432/hm?sslmode=disable
  Host: 127.0.0.1
  Port: 5432
  User: postgres
  Password: 123456
  DB: hm
  SSL: false
JWT:
  Secret: damingerdai
  Issuer: health-master
  Expire: 7200s
Redis:
  Host: 127.0.0.1
  Port: 6379
  Password:
  DB: 0
Logger:
  Level: debug
Smtp:
  Host:
  Port:
  Address:
  Password:
